// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entity.Model;

public partial class Address
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [Column("Address")]
    public string Address1 { get; set; }

    public bool IsActive { get; set; }

    public Guid UserId { get; set; }
}