// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entity.Model;

public partial class Todo
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Required]
    [StringLength(100)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [StringLength(100)]
    public string UpdateBy { get; set; }

    public bool? IsActive { get; set; }
}